name: Bump version

on:
  workflow_call:

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
          GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.12.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          git_name: github-actions[bot]
          git_email: github-actions[bot]@users.noreply.github.com
          changelog_increment_filename: body.md
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Release new version
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
