name: Bump version

on:
  workflow_call:

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GH_PAT }}"
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install commitizen
        run: python -m pip install -U pip commitizen
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.12.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          changelog_increment_filename: body.md
      - name: Release new version
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
