name: Check Code Quality and Performance
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/lint.yml@637ca306f8b5ac1585d48088528dd222ff891f58
  testing:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/test.yml@637ca306f8b5ac1585d48088528dd222ff891f58
