name: Check Code Quality and Performance
on:
  push:
    branches:
      - main
      - setup-github-actions
  pull_request:
    branches:
      - main

jobs:
  linting:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/lint.yml
  testing:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/test.yml
