name: Deploy new version
on:
  push:
    branches:
      - hotfix/versions


jobs:
  linting:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/lint.yml@hotfix/versions
  testing:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/test.yml@hotfix/versions
  bump_version:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/bump-version.yml@hotfix/versions
  upload_package:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/upload-package.yml@hotfix/versions
