name: Deploy new version

on:
  pull_request:
    types: 
      - closed
    branches: [ main ]
  workflow_dispatch:


jobs:
  bump_version:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/bump-version.yml@main
  upload_package:
    needs: bump_version
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/upload-package.yml@main

