name: Upload Python Package

on:
  release: 
    types: 
      - published
  workflow_dispatch:
    inputs:
      tag:  
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.ref_name }}"
    - name: Checkout input tag 
      if: ${{ github.event_name == "release" }}
      uses: actions/checkout@v2
      with: 
        ref: ${{ inputs.tag }}
    - name: Checkout release tag 
      if:  ${{ github.event_name == "workflow_dispatch" }}
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools build --user
    - name: Build package
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish package to PyPi
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

